### ISSUE TITLE
Bean Catcher

### ISSUE THREAD

**Issue by Blake5256** [aprilx246/ClubPenguin#1]
Bean Catcher game

**Comment by aprilx246** [comment]
This is proving a difficult task, with the code files I have I can get the game loaded but no bags seems to leave the truck for some reason, I beleive I am missing a file or some section of code

**Comment by aprilx246** [comment]
Hey! Bean Counters has now been added!! The sounds are still a bit glitchy so if you find any issues let me know and I'll patch them up, enjoy!
