### ISSUE TITLE
How can I run the PSA missions?

### ISSUE THREAD

**Issue by nico-mayora** [aprilx246/ClubPenguin#2]
I'm trying to use ruffle to open the first PSA mission, but all files are static or just have a blank screen. What's the "official" method for playing them?

**Comment by aprilx246** [comment]
Hello, the best method is to use the included flash player to open the files. Be sure to unzip the downloaded zip file first so that everything loads properly

**Comment by nico-mayora** [comment]
Where's that flash player? I was able to run astro barrier and pizzatron by cloning the repo, cd'ing into their folders, and running `ruffle game.swf`. I tried the same thing with the PSA missions to no avail.

**Comment by aprilx246** [comment]
Ah my apologies, the flash player was in a previous version but I must have removed it by accident, I shall add it back now to the root
