### ISSUE TITLE
Missing quest.swf files?

### ISSUE THREAD

**Issue by CutiePinsy** [aprilx246/ClubPenguin#3]
Hi there! I noticed recently that some of the files for the PSA Missions are missing when I extracted the zip.

Also, I had an additional problem where in Spy & Seek, when I try to enter the Ski Lodge, I'm stuck on a perma-loading screen. Mind if you can check that out as well for me? Again, thank you so much for preserving my childhood!

**Comment by JRatMain** [comment]
I'm having the same issue with the Ski Lodge in Spy & Seek - there might be a missing swf file. I downloaded the repo using git clone, so it shouldn't be an issue on my end.

**Comment by aprilx246** [comment]
Thanks for letting me know peeps! Indeed the files are missing on my end so I will try to find them, have you found any other permanent loading screens?

**Comment by CutiePinsy** [comment]
I know in Secrets of the Fur, the Coffee Shop has one.

**Comment by aprilx246** [comment]
Okay, I have found the rooms and put them where they should be! If you redownload the zip it all should work properly but don't hesitate to leave another comment if you find any more issues :)

**Comment by CutiePinsy** [comment]
I know there's one more issue which is the reason why I started up this thread originally- the quest.swf files are missing from some of the other PSA mission folders. And for some reason I can't find them if they are around somewhere. I'd love to play Waddle Squad again, but I can't! :[

**Comment by aprilx246** [comment]
Ah yes my apologies, I have no idea why the quest files are missing but yes I can add them!

**Comment by CutiePinsy** [comment]
Thank you very much! I'll close the issue for now, but if I find some more issues then I'll compilate some of the more glaring ones like infinite loading screens another time with another issue. Again, I'm very grateful that you responded quickly!

**Comment by aprilx246** [comment]
No problem, and if you're a fan of the missions be sure to check out my new project 'Operation Renaissance' where I'm trying to connect them all together :)
