### ISSUE TITLE
Perma-loading when using the piano in Clockwork Repairs

### ISSUE THREAD

**Issue by JRatMain** [aprilx246/ClubPenguin#4]
Hello!

When I was playing Clockwork Repairs, I tried using the piano in the stage and I noticed it wouldn't load - there must be a missing flash file that's causing it not to.

**Comment by aprilx246** [comment]
Hi! Indeed the Piano file was missing (it happens sometimes when I upload everything to GitHub), I've uploaded it now so if you redownload it should work properly

**Comment by JRatMain** [comment]
Yep, it's working now!

Though it might be a good idea to note that after completing the piano puzzle, the yellow puffle won't appear and you'll have to re-enter the Stage to see it.
